package de.schuette.cobra2D.entity.skills;

/**
 * @author Chris Entities implement this interface to be always stored in render
 *         queues generated by the map.
 */
public interface AlwaysVisible extends Renderable {

}
